services:
  api:
    build: .
    container_name: goodreads_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: goodreads
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: goodreads_db
    restart: always
    environment:
      POSTGRES_DB: goodreads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  postgres_data:
